{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-policies.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-policies.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: {{ include "kube-policies.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "kube-policies.fullname" . }}
  labels:
    {{- include "kube-policies.labels" . | nindent 4 }}
rules:
# Core Kubernetes resources
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - serviceaccounts
  - namespaces
  - nodes
  verbs: ["get", "list", "watch"]

# Apps resources
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch"]

# Extensions resources
- apiGroups: ["extensions"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - ingresses
  verbs: ["get", "list", "watch"]

# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  verbs: ["get", "list", "watch"]

# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs: ["get", "list", "watch"]

# Policy resources
- apiGroups: ["policies.kube-policies.io"]
  resources:
  - policies
  - policyexceptions
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Admission registration
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
  - validatingadmissionwebhooks
  - mutatingadmissionwebhooks
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Events
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "patch"]

# Metrics
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: {{ include "kube-policies.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-policies.fullname" . }}
  labels:
    {{- include "kube-policies.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-policies.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-policies.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: {{ include "kube-policies.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "kube-policies.fullname" . }}-monitoring
  labels:
    {{- include "kube-policies.labels" . | nindent 4 }}
rules:
# Prometheus monitoring
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: {{ include "kube-policies.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-policies.fullname" . }}-monitoring
  labels:
    {{- include "kube-policies.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-policies.fullname" . }}-monitoring
subjects:
- kind: ServiceAccount
  name: {{ include "kube-policies.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

