// Package auth provides constant-time verification and FIPS-CSPRNG generation
// of the shared internal bearer token used between the admission webhook,
// policy-manager, and dashboard.
//
// All token comparisons go through crypto/subtle.ConstantTimeCompare over
// fixed-length SHA-256 digests so that neither the contents nor the length of
// the configured token leak through a timing side-channel (CRY-WU-13,
// IAM-WU-07). Token material is generated from crypto/rand, which is served by
// the validated DRBG when the binary is built with the Go FIPS 140-3 module
// (GOFIPS140) and run with GODEBUG=fips140=on (CRY-WU-14).
package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"strings"
)

// bearerPrefix is the RFC 6750 Authorization scheme prefix.
const bearerPrefix = "Bearer "

// BearerToken extracts the credential from an "Authorization: Bearer <token>"
// header value. It returns "" when the header is absent or does not carry the
// Bearer scheme. The scheme name is matched case-sensitively to mirror the
// historic call-site behavior.
func BearerToken(header string) string {
	if !strings.HasPrefix(header, bearerPrefix) {
		return ""
	}
	return strings.TrimPrefix(header, bearerPrefix)
}

// TokenVerifier performs constant-time verification of a presented bearer
// token against one or more accepted tokens.
//
// A verifier may hold more than one accepted token to support zero-downtime
// rotation: during a rotation window both the new (current) and the old
// (previous) token are accepted so in-flight callers are not rejected while
// the secret propagates (CRY-WU-14). The zero value is an unconfigured
// verifier that rejects every token.
type TokenVerifier struct {
	// digests holds the SHA-256 digest of each accepted token. Comparing
	// fixed-length digests (rather than the raw strings) keeps the comparison
	// length-independent so the configured token length is never revealed.
	digests [][sha256.Size]byte
}

// NewTokenVerifier builds a verifier that accepts any of the supplied
// non-empty tokens. Empty strings are skipped so an unset previous token
// during normal (non-rotation) operation does not widen what is accepted, and
// an empty current token yields an unconfigured verifier (Configured()==false)
// rather than one that accepts the empty string.
func NewTokenVerifier(tokens ...string) *TokenVerifier {
	v := &TokenVerifier{}
	for _, t := range tokens {
		if t == "" {
			continue
		}
		v.digests = append(v.digests, sha256.Sum256([]byte(t)))
	}
	return v
}

// Configured reports whether at least one non-empty token is accepted. An
// unconfigured verifier rejects every presented token: an empty configured
// token must never act as a wildcard.
func (v *TokenVerifier) Configured() bool {
	return v != nil && len(v.digests) > 0
}

// Verify reports whether presented matches any accepted token. The comparison
// runs in constant time over fixed-length SHA-256 digests and always iterates
// every configured digest (no early return) so timing reveals neither which
// token matched nor how many tokens are accepted. An unconfigured verifier and
// an empty presented token both return false.
func (v *TokenVerifier) Verify(presented string) bool {
	if !v.Configured() || presented == "" {
		return false
	}
	got := sha256.Sum256([]byte(presented))
	var match int
	for i := range v.digests {
		// ConstantTimeCompare returns 1 on equal, 0 otherwise, in time
		// independent of the contents. OR-ing accumulates a match without
		// branching out of the loop.
		match |= subtle.ConstantTimeCompare(got[:], v.digests[i][:])
	}
	return match == 1
}

// VerifyHeader is a convenience wrapper that extracts the Bearer credential
// from an Authorization header value and verifies it in constant time.
func (v *TokenVerifier) VerifyHeader(authorizationHeader string) bool {
	return v.Verify(BearerToken(authorizationHeader))
}

// DefaultTokenBytes is the entropy, in bytes, of a generated internal token.
// 32 bytes (256 bits) comfortably exceeds the entropy of the previous
// 48-character alphanumeric Helm token while being drawn from a CSPRNG.
const DefaultTokenBytes = 32

// GenerateToken returns a URL-safe, unpadded base64 token carrying nBytes of
// entropy drawn from crypto/rand. When the binary is built with the Go
// FIPS 140-3 module, crypto/rand is served by the validated DRBG, so the token
// is generated by a FIPS-validated CSPRNG (CRY-WU-14). nBytes <= 0 is
// normalized to DefaultTokenBytes.
func GenerateToken(nBytes int) (string, error) {
	if nBytes <= 0 {
		nBytes = DefaultTokenBytes
	}
	b := make([]byte, nBytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("auth: read CSPRNG: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
